import { useState } from 'react';
import ToolView from '../components/ToolView';
import { useToast } from '../components/Toast';
import apiService, { GrammarResult, AIDetectResult, PlagiarismResult } from '../services/api';

/* ================================================================
   GRAMMAR VIEW
   ================================================================ */
export function GrammarView() {
    const [result, setResult] = useState<GrammarResult | null>(null);
    const [loading, setLoading] = useState(false);
    const { addToast } = useToast();

    const process = async (text: string) => {
        setLoading(true);
        try {
            const { data } = await apiService.grammar(text);
            setResult(data);
            addToast('Grammar check complete!', 'success');
        } catch (e: any) { addToast(e.response?.data?.error ?? e.message, 'error'); }
        finally { setLoading(false); }
    };

    return (
        <ToolView
            title="Grammar Checker"
            subtitle="Detect and auto-correct grammar, spelling, and style issues"
            processLabel="Check Grammar"
            isLoading={loading}
            onProcess={process}
            resultContent={result ? (
                <div>
                    <div className="grammar-side-by-side">
                        <div className="grammar-column">
                            <div className="grammar-column-title">Original</div>
                            <p>{result.original}</p>
                        </div>
                        <div className="grammar-column">
                            <div className="grammar-column-title">Corrected</div>
                            <p>{result.corrected}</p>
                        </div>
                    </div>
                    {result.changes.length > 0 ? (
                        <div className="grammar-error-list">
                            {result.changes.map((c, i) => (
                                <div key={i} className="grammar-error-item">
                                    {c.message}<br />
                                    <small>Suggestion: <strong>{c.suggestions.join(', ')}</strong></small>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="success-msg">✓ No grammar issues found!</div>
                    )}
                </div>
            ) : null}
        />
    );
}

/* ================================================================
   AI DETECT VIEW
   ================================================================ */
export function AIDetectView() {
    const [result, setResult] = useState<AIDetectResult | null>(null);
    const [loading, setLoading] = useState(false);
    const { addToast } = useToast();

    const process = async (text: string) => {
        setLoading(true);
        try {
            const { data } = await apiService.aiDetect(text);
            setResult(data);
            addToast('AI detection complete!', 'success');
        } catch (e: any) { addToast(e.response?.data?.error ?? e.message, 'error'); }
        finally { setLoading(false); }
    };

    const pct = result ? Math.round(result.ai_score * 100) : 0;
    const isAI = result?.is_ai_generated ?? false;
    const color = isAI ? 'var(--error)' : 'var(--success)';

    return (
        <ToolView
            title="AI Content Detector"
            subtitle="Analyse text to determine if it was generated by AI"
            processLabel="Detect AI Content"
            isLoading={loading}
            onProcess={process}
            resultContent={result ? (
                <div className="score-gauge">
                    <div className="gauge-circle" style={{ borderColor: color, boxShadow: `0 0 24px ${color}33` }}>
                        <span className="gauge-value" style={{ color }}>{pct}%</span>
                    </div>
                    <div className="gauge-label" style={{ color }}>{isAI ? 'AI-Generated' : 'Human-Written'}</div>
                    <div className="gauge-sublabel">{isAI ? 'High probability of AI content' : 'Content appears human-written'}</div>
                    <div className="analysis-grid">
                        <Stat value={result.analysis.lexical_diversity.toFixed(3)} label="Lexical Diversity" />
                        <Stat value={result.analysis.avg_sentence_length.toFixed(1)} label="Avg Sentence Len" />
                        <Stat value={result.analysis.sentence_length_variance.toFixed(1)} label="Sentence Variance" />
                        <Stat value={String(result.analysis.pattern_matches)} label="Pattern Matches" />
                    </div>
                </div>
            ) : null}
        />
    );
}

function Stat({ value, label }: { value: string; label: string }) {
    return <div className="analysis-stat"><div className="stat-value">{value}</div><div className="stat-label">{label}</div></div>;
}

/* ================================================================
   PLAGIARISM VIEW
   ================================================================ */
export function PlagiarismView() {
    const [result, setResult] = useState<PlagiarismResult | null>(null);
    const [loading, setLoading] = useState(false);
    const { addToast } = useToast();

    const process = async (text: string) => {
        setLoading(true);
        try {
            const { data } = await apiService.plagiarism(text);
            setResult(data);
            addToast('Plagiarism check complete!', 'success');
        } catch (e: any) { addToast(e.response?.data?.error ?? e.message, 'error'); }
        finally { setLoading(false); }
    };

    const origPct = result ? Math.round(result.originality_score * 100) : 0;
    const plagPct = result ? Math.round(result.plagiarism_score * 100) : 0;
    const color = origPct >= 80 ? 'var(--success)' : origPct >= 50 ? 'var(--warning)' : 'var(--error)';

    return (
        <ToolView
            title="Plagiarism Checker"
            subtitle="Check text originality with phrase-level matching"
            processLabel="Check Plagiarism"
            isLoading={loading}
            onProcess={process}
            resultContent={result ? (
                <div>
                    <div className="score-gauge" style={{ padding: '12px 0' }}>
                        <span className="gauge-value" style={{ color, fontSize: '2.2rem' }}>{origPct}%</span>
                        <div className="gauge-sublabel">Original Content</div>
                    </div>
                    <div className="bar-track">
                        <div className="bar-fill" style={{ width: `${origPct}%`, background: color }} />
                    </div>
                    <div className="bar-labels">
                        <span>Plagiarism: {plagPct}%</span><span>Originality: {origPct}%</span>
                    </div>
                    {result.matches.length > 0 ? (
                        <div className="match-list">
                            <p className="text-muted">{result.matches.length} phrase match(es) found:</p>
                            {result.matches.map((m, i) => (
                                <div key={i} className="match-item">
                                    <span className="match-phrase">"{m.phrase}"</span> at position {m.position}
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="success-msg">✓ No plagiarism detected</div>
                    )}
                </div>
            ) : null}
        />
    );
}
